---
name: "geodash-plugin-handlers"
controllers: []
directives: []
enumerations: []
templates: []
filters: []
handlers:
  - clickedOnMap.js
  - filterChanged.js
  - hideLayer.js
  - hideLayers.js
  - hideModal.js
  - layerLoaded.js
  - requestToggleComponent.js
  - selectStyle.js
  - showLayer.js
  - showLayers.js
  - showModal.js
  - stateChanged.js
  - switchBaseLayer.js
  #- leaflet/toggleComponent.js
  - ol3/toggleComponent.js
  - toggleFeatureLayer.js
  - toggleControl.js
  - viewChanged.js
  - zoomIn.js
  - zoomOut.js
  - zoomToLayer.js
  - zoomToLocation.js
  - flyToExtent.js
  - flyToLocation.js
  - flyToCurrentLocation.js
  - ol3/printMap.js
  - ol3/toggleFullScreen.js
  - startGeolocation.js
  - stopGeolocation.js
  - toggleGeolocation.js
schemas: []
modals: []
less: []
